manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar  # <-- RGB LED
      url-base: https://github.com/caksoylar
    - name: danielelombardo  # <-- mouse wiggler
      url-base: https://github.com/danielelombardo
    - name: danielelombardo  # <-- dongle display
      url-base: https://github.com/danielelombardo
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main  # v0.3-branch  # <-- stable branch
      import: app/west.yml
    - name: zmk-rgbled-widget  # <-- RGB LED 
      remote: caksoylar
      revision: main
    - name: zmk-anti-idle # <-- mouse wiggler
      remote: danielelombardo
      revision: main
    - name: zmk-dongle-display # <-- dongle display
      remote: danielelombardo
      revision: main
  self:
    path: config